# -*- coding: utf-8 -*-
"""unemploymentAnalysisProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YME6q8hDKFDCZeXzL_HkLVV2LPJWRymy
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from datetime import datetime
from google.colab import files

uploaded = files.upload()
data = pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')

data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month

label_encoder_region = LabelEncoder()
label_encoder_region1 = LabelEncoder()
data['Region'] = label_encoder_region.fit_transform(data['Region'].astype(str).str.strip())
data['Region.1'] = label_encoder_region1.fit_transform(data['Region.1'].astype(str).str.strip())

features = [
    'Region', 'Region.1', 'Estimated Employed',
    'Estimated Labour Participation Rate (%)', 'longitude', 'latitude', 'Year', 'Month'
]

target = 'Estimated Unemployment Rate (%)'

X = data[features]
y = data[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
print("Feature Importances:", model.feature_importances_)

from google.colab import drive
drive.mount('/content/drive')